COVERAGE_MIN ?= 80
COVERAGE_PROFILE ?= .vial/coverage.out
GOEXE := $(shell go env GOEXE)
VIAL_BIN ?= bin/vial$(GOEXE)

.PHONY: test coverage race vet integrations examples benchmark build install dev check

test:
	go test ./...
	cd vialgrpc && go test ./...
	cd vialws && go test ./...

coverage:
	mkdir -p $(dir $(COVERAGE_PROFILE))
	go test -coverpkg=./... -coverprofile=$(COVERAGE_PROFILE) ./...
	@go tool cover -func=$(COVERAGE_PROFILE) | awk -v min="$(COVERAGE_MIN)" '/^total:/ { found=1; gsub(/%/, "", $$3); printf "coverage: %.1f%% (minimum %.1f%%)\n", $$3, min; if ($$3 + 0 < min) failed=1 } END { exit (!found || failed) }'

race:
	go test -race ./...
	cd vialgrpc && go test -race ./...
	cd vialws && go test -race ./...

vet:
	go vet ./...
	cd vialgrpc && go vet ./...
	cd vialws && go vet ./...

integrations:
	cd vialgrpc && go test -cover ./...
	cd vialws && go test -cover ./...

examples:
	cd examples/securecookie && go test ./...
	cd examples/websocket && go test ./...
	cd examples/grpc && go test ./...
	cd examples/database && go test -run '^$$' ./...

benchmark:
	go test -run '^$$' -bench '^BenchmarkHTTP$$' -benchmem -count=5 ./tests/vial

build:
	mkdir -p $(dir $(VIAL_BIN))
	go build -o $(VIAL_BIN) ./cmd/vial

install:
	go install ./cmd/vial

dev: build
	$(VIAL_BIN) dev ./examples/hello

check: coverage integrations race vet examples build
